# Generated by Django 4.2.4 on 2023-08-24 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('day', 'venue', 'slot')},
        ),
    ]
